version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"